/** Southeast Alaska communities and regional values. SPEC §14. */
export const SE_COMMUNITIES = [
  "Angoon",
  "Coffman Cove",
  "Craig",
  "Edna Bay",
  "Elfin Cove",
  "Excursion Inlet",
  "Gustavus",
  "Haines",
  "Hollis",
  "Hoonah",
  "Hydaburg",
  "Hyder",
  "Juneau",
  "Kake",
  "Kasaan",
  "Ketchikan",
  "Klawock",
  "Klukwan",
  "Metlakatla",
  "Meyers Chuck",
  "Naukati Bay",
  "Pelican",
  "Petersburg",
  "Point Baker",
  "Port Alexander",
  "Port Protection",
  "Saxman",
  "Sitka",
  "Skagway",
  "Tenakee Springs",
  "Thorne Bay",
  "Whale Pass",
  "Wrangell",
  "Yakutat",
  "Prince of Wales Island (regional)",
  "Southeast Alaska (regional)",
  "Statewide",
] as const;

export type SeCommunity = (typeof SE_COMMUNITIES)[number];

/** Focus areas used on organizations, funders, and opportunities. SPEC §14. */
export const FOCUS_AREAS = [
  "Arts & Culture",
  "Language Revitalization",
  "Education & Youth",
  "Health & Wellness",
  "Behavioral Health",
  "Food Security & Subsistence",
  "Housing",
  "Economic Development & Small Business",
  "Fisheries & Mariculture",
  "Tourism",
  "Environment & Conservation",
  "Outdoor Recreation & Trails",
  "Infrastructure & Energy",
  "Transportation & Harbors",
  "Public Safety & Emergency Preparedness",
  "Community Facilities",
  "Workforce & Training",
  "Elders & Seniors",
  "Broadband & Technology",
  "Historic Preservation",
] as const;

export type FocusArea = (typeof FOCUS_AREAS)[number];
